# .circleci/config.yml
#
# This file configures the CircleCI 2.0 build.
#
# Documentation:
# - Overview: https://circleci.com/docs/2.0/workflows/
# - Caching: https://circleci.com/docs/2.0/caching/
#
# Things to know:
# - every job is a container
# - cache is used for data that can potentially be reused between builds, provided we can
#   be sure it will not influence the build result other than by speeding it up.
# - cache is immutable. Sometimes we need to flush the cache, but we can't. That's why there is this
#   `v1-` at the beginning. Increment it when you need to change the cache content.
# - because we use `npm ci`, we cache the `~/.npm` directory and not `node_modules` which
#   is erased by `npm ci`.
# - to make sure the cache is indexed by the `package.json` and `package-lock.json` files,
#   we concatenate them into a temporary file whose checksum we use as part of the cache key.
# - for data that is specific to a build (commit), like the source code downloaded from github,
#   we use Circle CI's workspace feature to transport it between jobs.

version: 2.1

commands:
  npm_ci:
    description: "Run 'npm ci' with cache"
    parameters:
      cache_key:
        type: string
    steps:
      - run: cat package*.json > cachekey
      - restore_cache:
          key: v7-<< parameters.cache_key >>-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-<< parameters.cache_key >>-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - master
                - math
                - preview
                - gh-pages
                - /release-.*/

      - api_build_and_test:
          requires:
            - checkout

      - ember_build:
          directory: mon-pix
          parallelism: 3
          requires:
            - checkout

      - ember_build:
          directory: orga
          requires:
            - checkout

      - ember_build:
          directory: certif
          requires:
            - checkout

      - ember_build:
          directory: admin
          requires:
            - checkout

      - e2e_test:
          requires:
            - checkout
          filters:
            branches:
              ignore:
                - dev

jobs:
  checkout:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/pix
    steps:
      - checkout
      - run: rm -rf .git/
      - persist_to_workspace:
          root: ~/pix
          paths:
            - .

  api_build_and_test:
    docker:
      - image: circleci/node:10.15.1
      - image: postgres:10-alpine
        environment:
          POSTGRES_USER: circleci
    working_directory: ~/pix/api
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: api
      - run:
          command: |
            npm run lint
            npm test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci

  ember_build:
    parameters:
      directory:
        type: string
      parallelism:
        type: integer
        default: 1
    docker:
      - image: circleci/node:10.15.1-browsers
        environment:
          # See https://git.io/vdao3 for details.
          JOBS: 2
    working_directory: ~/pix/<< parameters.directory >>
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: << parameters.directory >>
      - run: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  e2e_test:
    docker:
      - image: cypress/browsers:chrome69
      - image: postgres:10-alpine
        environment:
          POSTGRES_USER: circleci
    working_directory: ~/pix/high-level-tests/e2e
    steps:
      - attach_workspace:
          at: ~/pix
      - npm_ci:
          cache_key: e2e

      - run:
          working_directory: ~/pix/api
          command: cat package*.json > cachekey-api
      - restore_cache:
          keys:
            - v7-api-npm-{{ checksum "~/pix/api/cachekey-api" }}
      - run:
          working_directory: ~/pix/api
          background: true
          environment:
            DATABASE_URL: 'postgres://circleci@localhost:5432/circleci'
          command: npm ci && npm start

      - run:
          working_directory: ~/pix/mon-pix
          command: cat package*.json > cachekey-mon-pix
      - restore_cache:
          keys:
            - v7-mon-pix-npm-{{ checksum "~/pix/mon-pix/cachekey-mon-pix" }}
      - run:
          environment:
            # See https://git.io/vdao3 for details.
            JOBS: 2
          working_directory: ~/pix/mon-pix
          background: true
          command: npm ci && npm start

      - run:
          environment:
            DATABASE_URL: 'postgres://circleci@localhost:5432/circleci'
          command: |
            wget --retry-connrefused -T 60 -qO- http://localhost:4200
            wget --retry-connrefused -T 60 -qO- http://localhost:3000/api
            npm run cy:run
